quarkus:
  log:
    level: debug
  http:
    access-log:
      enabled: true
  mongodb:
    database: klubi
    devservices:
      properties:
        uuidRepresentation: STANDARD

"%prod":
  quarkus:
    mongodb:
      connection-string: mongodb://localhost:27017/?uuidRepresentation=STANDARD
